const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync(require('node:path').join(__dirname,'../zhiyeyaoshi.user.js'),'utf8');
const values={},prompts=[];let items=[];let nextAnswer='1.C';
const doc={hidden:false,readyState:'loading',addEventListener(){},getElementById(){return null},querySelectorAll(s){return s==='.examination-body-item'?items:[]},querySelector(){return null}};
const sandbox={URL:URL,console:{log(){},warn(){},error(){},info(){}},document:doc,navigator:{},crypto:require('node:crypto').webcrypto,performance,Blob,Map,Set,AbortController,Promise,Date,Number,Math,JSON,sessionStorage:{getItem(){return null},setItem(){}},GM_getValue:(k,d)=>k in values?values[k]:d,GM_setValue:(k,v)=>values[k]=v,GM_addStyle(){},setTimeout(){return 1},clearTimeout(){},setInterval(){return 1},clearInterval(){},addEventListener(){},location:{hash:'#/examination'}};sandbox.window=sandbox;
const hooks='window.h={review:collectReviewAnswersAndCorrect,prompt:buildCorrectionPrompt,context:buildRetryHistoryContext,noReviewPrompt:buildNoReviewCorrectionPrompt,limit:normalizeExamRetryLimit,reset:resetExamRetryState,wrong:confirmedWrongAnswers,failed:failedAttemptAnswers,memory:examAnswerMemory,setRound:n=>examAttemptCount=n,setLast:q=>{lastAttemptData.clear();q.forEach(x=>lastAttemptData.set(x.title,x));},handleFailure:handleFailedExamResult,nav:navigateToAllInOnePhase,advance:advanceAllInOnePhaseIfExpected,getTransition:()=>allInOneTransitionPending,getPhase:()=>allInOnePhase,setPhase:p=>{isAllInOneMode=true;allInOnePhase=p;},pause:()=>setRuntimeServiceActive(false),resume:()=>{isServiceActive=true},setMemory:(t,a)=>examAnswerMemory.set(t,a)};askAiForAnswer=(p)=>{window.prompts.push(p);return window.delayAi ? new Promise((resolve,reject)=>{window.resolveAi=resolve;window.rejectAi=reject}) : Promise.resolve(window.nextAnswer)};returnToExamListAfterReview=()=>{};window.skips=0;recordFailedExamAndContinue=()=>{window.skips++};';
sandbox.prompts=prompts;sandbox.nextAnswer=nextAnswer;
vm.runInNewContext(source.replace(/\}\)\(\);\s*$/,hooks+'})();'),sandbox);
const h=sandbox.h;
function item(title,answer,wrong=true,options=['A.甲','B.乙','C.丙','D.丁']){return {querySelector(s){if(s==='.examination-body-title')return {innerText:'1、'+title};if(s==='.details-state.danger')return wrong?{innerText:'回答错误'}:null;if(s==='.examination-details em')return {innerText:answer};return null},querySelectorAll(){return options.map(innerText=>({innerText}))}}}
(async()=>{
sandbox.location.hash="#/publicDemand";h.setPhase("public-article");assert.equal(h.nav(),true);assert.equal(h.getTransition(),false,"same route must not wait for hashchange");assert.equal(h.advance("public-article"),true);assert.equal(h.getPhase(),"specialized-exam");assert.equal(h.getTransition(),true,"different route must await actual hashchange");sandbox.location.hash="#/examination";
for(const [value,expected] of [[undefined,3],['',3],[null,3],['bad',3],[-1,0],[0,0],[1,1],[2,2],[3,3],[5,3],[2.9,2]])assert.equal(h.limit(value),expected);
items=[item('测试单选','A'),item('已答对','B',false)];h.setRound(1);h.review();await Promise.resolve();assert.equal(h.memory.get('已答对'),'B');assert.match(prompts.at(-1),/第1轮：A/);
items=[item('测试单选','B')];h.setRound(2);h.review();await Promise.resolve();assert.match(prompts.at(-1),/第1轮：A；第2轮：B/);assert.equal(h.memory.get('测试单选'),'C');
sandbox.nextAnswer='1.A';h.setRound(3);h.review();await Promise.resolve();assert.equal(h.memory.has('测试单选'),false,'must not reuse confirmed wrong');assert.equal(h.wrong.values().next().value.length,3,'one record per round');
assert.match(h.context([item('测试单选','')]),/第1轮：A；第2轮：B/);h.reset();assert.equal(h.wrong.size,0);assert.equal(h.failed.size,0);
const q={title:'多选测试',options:['A.甲','B.乙','C.丙'],answer:'AB'};h.setRound(1);h.setLast([q]);let p=h.noReviewPrompt();assert.match(p,/第1轮：AB/);h.setRound(2);h.setLast([{...q,answer:'BC'}]);p=h.noReviewPrompt();assert.match(p,/第1轮：AB；第2轮：BC/);assert.match(p,/不能把所有历史作答都认定为错误/);h.noReviewPrompt();assert.equal(h.failed.values().next().value.length,2);
items=[item('多选测试','BA',true,q.options)];h.setRound(3);sandbox.nextAnswer='1.AB';h.review();await Promise.resolve();assert.equal(h.memory.has('多选测试'),false,'wrong combo order normalized');sandbox.nextAnswer='1.AC';h.review();await Promise.resolve();assert.equal(h.memory.get('多选测试'),'AC','wrong combo does not exclude each individual option');
h.reset();values.sclpa_exam_max_retries=0;h.handleFailure();assert.equal(sandbox.skips,1,'0 skips retries without asking AI');h.reset();values.sclpa_exam_max_retries=5;h.setRound(3);h.handleFailure();assert.equal(sandbox.skips,2,'legacy values above 3 cannot cause fourth retry');
h.reset();sandbox.delayAi=true;items=[item('迟到结果测试','A')];h.review();h.reset();sandbox.resolveAi('1.C');await Promise.resolve();await Promise.resolve();assert.equal(h.memory.has('迟到结果测试'),false,'reset must invalidate correction');
h.review();sandbox.location.hash='#/publicDemand';sandbox.resolveAi('1.C');await Promise.resolve();await Promise.resolve();assert.equal(h.memory.has('迟到结果测试'),false,'leaving route must invalidate correction');
sandbox.location.hash='#/examination';h.review();h.pause();sandbox.resolveAi('1.C');await Promise.resolve();await Promise.resolve();assert.equal(h.memory.has('迟到结果测试'),false,'pause must invalidate correction');h.resume();
console.log('PASS: late corrections ignored after reset, route exit and pause');
console.log('PASS: cumulative confirmed/unknown history, reset, multiselect combinations, known-wrong rejection, retry limits and zero skip');
})().catch(e=>{console.error(e);process.exitCode=1});
